---
# tasks file for docker_compose
- name: Install gpg
  apt:
    name: gpg 

- name: Add docker signing key, will not download if present
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add docker repository into sources list
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable
    state: present

- name: Install a list of packages
  apt:
    pkg:
      - ca-certificates 
      - curl 
      - gnupg 
      - lsb-release
      - docker-ce
      - docker-ce-cli
      - docker-compose
      - containerd.io
      - docker-compose-plugin
      - rsync
- name: Make sure we have a 'docker' group
  group:
    name: docker
    state: present

- name: make sure admin user is in docker group
  user:
    name: "admin"
    state: "present"
    groups: docker
        
- name: create directory
  file:
    path: /tmp/app
    state: directory

- name: create directory
  file:
    path: "/tmp/app"
    state: directory

- name: sync of file
  synchronize:
    src: .
    dest: /tmp/app

- name: test docker-compose
  docker_compose:
    project_src: /tmp/app
    files: docker-compose.yml
    state: present
  register: __docker_compose_output

- name: debug
  debug: 
    var: __docker_compose_output

